#include "object/Bool.h"
#include "object/Float.h"
#include "object/Func.h"
#include "object/Int.h"
#include "object/NativeFunc.h"
#include "object/Null.h"
#include "object/String.h"
#include "object/Object.h"